### ISSUE TITLE
Toolbox error

### ISSUE THREAD

**Issue by TomWaterat** [NSW-OEH-EMS-KST/grid-garage-3#196]
See below (when right-click on toolbox):
![gg_toolbox_error01](https://user-images.githubusercontent.com/4453449/30305550-cd53a2fa-97b6-11e7-8ef1-75000b6d86a2.JPG)

**Comment by TomWaterat** [comment]
Getting this error:

Traceback (most recent call last):
  File "<string>", line 47, in <module>
  File "C:\Data\grid-garage\tools\cdf\extract_timeslices.py", line 3, in <module>
    from netCDF4 import Dataset
  File "C:\Data\grid-garage\netCDF4\__init__.py", line 3, in <module>
ImportError: No module named _netCDF4
